name: Keep Codespace Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep alive ping
        run: echo "Keeping Codespace Active"
